import type { ContractAnalysis } from "@/types/analysis"

function esc(s: string) {
  return s
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;")
}

export function buildAnalysisReportHtml(
  title: string,
  analysis: ContractAnalysis,
): string {
  const rf = analysis.red_flags
    .map(
      (f) => `
      <div class="rf">
        <div class="rf-head"><strong>${esc(f.clause)}</strong> <span class="sev">${esc(f.severity)}</span></div>
        <p>${esc(f.explanation)}</p>
        <p><em>Suggestion:</em> ${esc(f.suggestion)}</p>
      </div>`,
    )
    .join("")

  const dates = analysis.key_dates
    .map((d) => `<li><strong>${esc(d.label)}</strong> — ${esc(d.date)}</li>`)
    .join("")

  const you = analysis.obligations.you.map((x) => `<li>${esc(x)}</li>`).join("")
  const them = analysis.obligations.them
    .map((x) => `<li>${esc(x)}</li>`)
    .join("")
  const qs = analysis.questions_to_ask.map((q) => `<li>${esc(q)}</li>`).join("")

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <title>${esc(title)} — ClearSign Report</title>
  <style>
    body { font-family: Inter, system-ui, -apple-system, sans-serif; color: #0f172a; margin: 0; padding: 32px; line-height: 1.55; }
    .header { border-bottom: 4px solid #E8401C; padding-bottom: 16px; margin-bottom: 24px; }
    .brand { color: #1A3C5E; font-size: 28px; font-weight: 800; letter-spacing: -0.02em; }
    .tag { display: inline-block; background: #1A3C5E; color: #fff; padding: 4px 10px; border-radius: 999px; font-size: 12px; font-weight: 600; }
    .risk { font-size: 42px; font-weight: 800; color: #1A3C5E; }
    h2 { color: #1A3C5E; margin-top: 28px; font-size: 18px; }
    .rf { border: 1px solid #e2e8f0; border-radius: 12px; padding: 14px 16px; margin: 10px 0; }
    .rf-head { display: flex; justify-content: space-between; gap: 12px; align-items: baseline; }
    .sev { font-size: 12px; font-weight: 700; color: #E8401C; }
    .footer { margin-top: 40px; padding-top: 16px; border-top: 1px solid #e2e8f0; font-size: 12px; color: #64748b; }
  </style>
</head>
<body>
  <div class="header">
    <div class="brand">ClearSign</div>
    <div style="margin-top:8px;color:#64748b;font-size:14px">AI contract analysis report</div>
  </div>
  <h1 style="margin:0 0 8px;font-size:22px">${esc(title)}</h1>
  <div style="margin-bottom:16px"><span class="tag">${esc(analysis.contract_type)}</span></div>
  <div>Risk score: <span class="risk">${analysis.risk_score}</span> / 10</div>
  <h2>Summary</h2>
  <p>${esc(analysis.summary)}</p>
  <h2>Key dates</h2>
  <ul>${dates || "<li>No specific dates identified.</li>"}</ul>
  <h2>Your obligations</h2>
  <ul>${you || "<li>None listed.</li>"}</ul>
  <h2>Their obligations</h2>
  <ul>${them || "<li>None listed.</li>"}</ul>
  <h2>Red flags</h2>
  ${rf || "<p>No major red flags flagged.</p>"}
  <h2>Questions to ask</h2>
  <ul>${qs || "<li>—</li>"}</ul>
  <div class="footer">
    ClearSign provides AI-generated analysis for informational purposes only. This is NOT legal advice.
    Generated by clearsign.app
  </div>
</body>
</html>`
}
